width: 800
height: 800
luminosity-label: '%lumi% fb^{-1} (13 TeV)'
experiment: "CMS"
extra-label: "Preliminary"
root: '/home/fynu/amertens/scratch/cmssw/CMSSW_7_4_15/src/cp3_llbb/CommonTools/histFactory/16_01_11/build/'
luminosity: 2200.00
luminosity-error: 0
